// import { generateId } from "./utilities";
// const HOUR_MILLIS = 1000 * 60 * 60;
// const DAY_MILLIS = HOUR_MILLIS * 24;

export const Tasks = [
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-SyslL6DUirw7",
    title: "Refreshing on /projects/[projectId]",
    description:
      "Strange errors when refreshing when viewing a Project. It seems like it cant fetch tasks, and when pressing back, none of the ProjectChooser cards have correct hex_color",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-10T23:31:16.451Z",
    lastModifiedDateTime: "2025-10-10T23:31:16.451Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-LewxVJgCIEL7",
    title: "Deleting a Task Bug",
    description: "TaskDetails attempts to re-render with the now deleted Task",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-10T23:05:31.020Z",
    lastModifiedDateTime: "2025-10-10T23:05:31.020Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-FODBTPisf1OF",
    title: "Check Routes",
    description:
      "Fixed another bug with snake_case/camelCase. Need to go through all route consumers & check what they're sending in their 'body', as I can already see some discrepancies in the Context files.",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-10T00:00:37.729Z",
    lastModifiedDateTime: "2025-10-11T00:38:31.651Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-QfEGWWqAqCqe",
    title: "Backup DB",
    description:
      "Since I've been using the 'Todo App' project to log bugs/improvements, it's become valuable to save. console.log the Contexts and copy/paste new JSONs into placeholder-data. This will enable adding new props to Project & Task.",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-09T23:35:55.265Z",
    lastModifiedDateTime: "2025-10-09T23:35:55.265Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-lC8yeflMPz8Q",
    title: "Add Default Keyword to Applicable Components",
    description:
      "'default' should be used in the scenarios where the component exported matches the name of the file. Ex: 'import { TaskDetails }' should be 'import TaskDetails' (no brackets)",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-09T23:29:25.990Z",
    lastModifiedDateTime: "2025-10-09T23:29:25.990Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-UJD519jO9HCg",
    title: "Implement LootBox Component",
    description:
      "animation.tsx could be used to add some interactivity to the dashboard. Put a button next to 'Projects' that lowers the platform and raises it with something to display (oot sound?). Rubiks, a firework, pre-made project, TAB key (future of CS), etc. Could show text like '1 / 6 unlocked' showing images with odds beneath.",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-09T22:34:31.717Z",
    lastModifiedDateTime: "2025-10-10T00:07:05.126Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-HWVEHu4Gzg2K",
    title: "Add Rollback to Update/Delete",
    description:
      "Need to add rollback logic for Tasks and Projects for the other CRUD operations. This can cause problems when updating a Task to have the same name as another Task in the Project (will fail silently).",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-09T21:29:13.369Z",
    lastModifiedDateTime: "2025-10-09T23:19:51.583Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-7uWxq4rHUTFi",
    title: "ExpectedCompletionDateTime",
    description:
      "Creating a Task with an expectedCompletionDateTime doesn't seems to persist.",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-09T21:13:43.425Z",
    lastModifiedDateTime: "2025-10-10T00:01:40.981Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-5D8q1GYB94Md",
    title: "Back Button bug",
    description:
      "After editing a Project (description), the user is returned to the ProjectPage. The user will then need to click the back button twice to get it to work. Pretty sure its because router.replace()",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-09T13:34:59.581Z",
    lastModifiedDateTime: "2025-10-09T18:52:29.371Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-6VcmRw11CRtN",
    title: "Fix addProject & addTask context methods",
    description:
      "The server logic for these are still handled on the component/page using routes. Should update to match pattern for updating & deleting.",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-09T13:10:16.084Z",
    lastModifiedDateTime: "2025-10-09T21:15:44.872Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-mx775i0qZsYU",
    title: "Update TaskFormAccordion to use new generic Accordion component",
    description: null,
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-09T13:00:40.821Z",
    lastModifiedDateTime: "2025-10-09T18:46:50.919Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-IwJAxlH1RJhh",
    title: "Need to Fix Mismatches with Headers",
    description: "Make sure all page headers use similar sizings and margins",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-07T17:36:27.109Z",
    lastModifiedDateTime: "2025-10-07T19:39:36.261Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-DbO5F9LVEsbc",
    title: "Fix Bugs",
    description:
      "Back Button navigation is broken after deleting a project\nFix issues with production build and server persistence",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-07T02:28:55.072Z",
    lastModifiedDateTime: "2025-10-07T16:45:12.997Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-ezEC216gjS1C",
    title: "Persist Newlines",
    description:
      "This would raise some questions in the UI, like 'how much to now show on TaskCards?'. Also would need to add a 'show more' on TaskPage.",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-05T22:44:54.952Z",
    lastModifiedDateTime: "2025-10-05T22:44:54.952Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-tFOC5UHdk3Qi",
    title: "Show Task Completion",
    description:
      "ProjectPage should show how many tasks have been completed with pie chart. This could also show the chart in terms of 'tags'?",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-05T22:43:15.722Z",
    lastModifiedDateTime: "2025-10-05T22:43:15.722Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-NNcaZvqNJJAO",
    title: "Search/Filtering on ProjectChooser",
    description:
      "Can use a similar UI to what was done on TasksPage. With so many Tasks in this project now, maybe a Pagination component is needed as well?",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-05T15:40:13.530Z",
    lastModifiedDateTime: "2025-10-09T21:16:42.295Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-JLCkJt902VHx",
    title: "Create 'Completed Projects' on /projects",
    description:
      "Need to add section for Projects that have been completed. Could either check if all Tasks are marked isDone, but should probably add 'isDone' prop to Project. This new section could be in an accordion in ProjectChooser.",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-05T15:39:04.779Z",
    lastModifiedDateTime: "2025-10-05T15:39:04.779Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-uXvG8Hh28xUO",
    title: "Fix Back Navigation after Editing Projects",
    description:
      "Similar to Tasks, can press the BackButton to try and navigate to a freshly deleted project. Just need to manually set router cache and refresh.",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-05T15:30:35.047Z",
    lastModifiedDateTime: "2025-10-05T21:52:51.366Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-rwIdKGeKdu83",
    title: "Handle Promises throughout App",
    description:
      "Both contexts in the app manage the routes for updating the db. Because of this, all the methods that update the context are 'async', meaning they return a Promise. Should check all context consumers to check if handling promises provides benefits.",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-05T15:18:31.556Z",
    lastModifiedDateTime: "2025-10-05T15:18:31.556Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-EuuKgxvq3Nqz",
    title: "Make sure TaskList is synchronized between /projects & /tasks",
    description:
      "Updating a Task in either of these pages does not reflect on the other. The changes are reflected immediately on their respective UIs & on the server, but not each other. Likely a useEffect situation in TaskList",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-04T00:34:09.087Z",
    lastModifiedDateTime: "2025-10-07T17:29:52.023Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-z01u7hYbNUyr",
    title: "Tasks & Projects need to be updated on /(dashboard) page",
    description:
      "Using the proper contexts for the Tasks & Projects shown on the dashboard should resolve the issue",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-03T00:29:53.250Z",
    lastModifiedDateTime: "2025-10-03T23:36:25.451Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-L8yGOeyXX5E9",
    title: "Bugs With /tasks Page",
    description:
      "Applying filters/sorts then pressing 'Back to Dashboard' doesn't work (filters change URL & thus router)\n\nNeed to implement context work to prevent all Tasks from showing all the time",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-03T00:27:57.892Z",
    lastModifiedDateTime: "2025-10-04T00:28:45.746Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-HYigaIZw2Usz",
    title: "Task.completionDateTime ",
    description:
      "Should think about adding another property to show when the Task was marked 'done'.",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-02T20:10:57.069Z",
    lastModifiedDateTime: "2025-10-02T20:10:57.069Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-8KxEuJjHpDeH",
    title: "Fix 'Delete' & 'Mark as Done' buttons",
    description: "TaskDetails: Need to fix quick action buttons",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-02T15:42:45.074Z",
    lastModifiedDateTime: "2025-10-02T19:11:55.903Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-kGqOiAKi",
    title: "Implement Context for Tasks & Projects",
    description:
      "To fix the issues with the UI not immediately updating with form submissions, I decided to try implementing React Context. Context acts as a sort of useState that can be shared & imported in Components, which should allow the UI to force a rerender",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-01T22:54:09.474Z",
    lastModifiedDateTime: "2025-10-02T23:50:36.759Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-4aG3uNrM",
    title: "Back Button Bug",
    description:
      "Pressing 'Cancel' when editing a Task will cause a bug similar to the original issue. Need to just 'flush' the router, similar to what's done when updated.\n\nEDIT: Changed Link -> Button and used router.back() for onClick handler.",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-01T01:16:04.062Z",
    lastModifiedDateTime: "2025-10-01T22:20:21.952Z",
  },
  {
    projectId: "PRO-GvUg9na4",
    id: "TSK-cUS3Si0x",
    title: "Coffee Mug Punch",
    description:
      "Using 3JS to create a simple 1st person animation of someone holding a coffee cup, sitting in front of pc, then using the mug as brass knuckles to punch the screen",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-10-01T01:07:18.572Z",
    lastModifiedDateTime: "2025-10-01T01:07:18.572Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-H0vFswh9",
    title: "Make Accordion Height Dynamic",
    description:
      "When the content inside the accordion changes (contentHeight) the accordion should resize to accommodate for that height. This should be possible using an observer. Or maybe the handling of the onSubmit callback could signal that the content has changed.\n\nFIX: Added onError? callback to TaskForm & resize method in TaskFormAccordion",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-30T20:03:25.914Z",
    lastModifiedDateTime: "2025-10-02T15:38:29.121Z",
  },
  {
    projectId: "PRO-SHOPPING",
    id: "TSK-CJ0vASyI",
    title: "Towels",
    description: null,
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-30T14:41:02.749Z",
    lastModifiedDateTime: "2025-09-30T14:41:02.749Z",
  },
  {
    projectId: "PRO-SHOPPING",
    id: "TSK-9QkS2VC9",
    title: "Napkins",
    description: null,
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-30T14:37:28.295Z",
    lastModifiedDateTime: "2025-09-30T14:37:28.295Z",
  },
  {
    projectId: "PRO-SHOPPING",
    id: "TSK-2POwx3OX",
    title: "Steamed Hams",
    description: "For the steamed clams we're having!",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-30T14:35:13.687Z",
    lastModifiedDateTime: "2025-09-30T14:35:13.687Z",
  },
  {
    projectId: "PRO-SHOPPING",
    id: "TSK-4bpy48ob",
    title: "Basketball",
    description: "The old one is about to pop!",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-30T14:34:26.913Z",
    lastModifiedDateTime: "2025-09-30T14:34:26.913Z",
  },
  {
    projectId: "PRO-SHOPPING",
    id: "TSK-nyzgvJUT",
    title: "Lao Gan Ma",
    description: "老干妈",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-30T00:41:25.553Z",
    lastModifiedDateTime: "2025-09-30T00:41:25.553Z",
  },
  {
    projectId: "PRO-SHOPPING",
    id: "TSK-D4LzpRp0",
    title: "Spam",
    description: "Get the teriyaki version or none at all!",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-30T00:38:30.638Z",
    lastModifiedDateTime: "2025-09-30T00:38:30.638Z",
  },
  {
    projectId: "PRO-FwHRKp5O",
    id: "TSK-jKsI7GM4",
    title: "Outer Ring: 3",
    description:
      "Once the max growth is reached, the outer ring is shrunk back to the same radius to the inner circle, essentially making it disappear.\n\nOne final concentric circle is emitted when the outer ring radius matches the inner circles'.",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-27T00:33:11.401Z",
    lastModifiedDateTime: "2025-10-05T15:34:59.844Z",
  },
  {
    projectId: "PRO-FwHRKp5O",
    id: "TSK-XvXSmmuj",
    title: "Outer Ring: 2",
    description:
      "Outer Ring and inner circle grow for the same amount of time, but the outer ring's start is delayed.\n\n2 concentric circles continue to grow from outer ring with same speed after max size is reached. These are faded out quickly.",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-27T00:07:12.845Z",
    lastModifiedDateTime: "2025-10-05T15:34:54.545Z",
  },
  {
    projectId: "PRO-FwHRKp5O",
    id: "TSK-g9RbeVih",
    title: "Outer Ring: 1",
    description:
      "Has two parts:\n- Full outline\n- Thicker arc (~12% diameter) that rotates around the inner circle along the outline\n- Speed of arc is: 1 rotation ~ 2s",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-27T00:01:40.826Z",
    lastModifiedDateTime: "2025-10-05T15:34:48.810Z",
  },
  {
    projectId: "PRO-FwHRKp5O",
    id: "TSK-u1M0crUr",
    title: "Inner Circle",
    description:
      "This is the circle which holds the icon.\n\n1: Grows for 1s\n2: Shrinks (bounces) back to starting size\n3: Icon is faded out by end of step 2\n4: Check mark is drawn inside circle",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-26T23:56:19.600Z",
    lastModifiedDateTime: "2025-10-05T15:34:43.674Z",
  },
  {
    projectId: "PRO-SHOPPING",
    id: "TSK-VmIcuz4T",
    title: "Candy",
    description: null,
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-26T23:28:42.007Z",
    lastModifiedDateTime: "2025-09-26T23:28:42.007Z",
  },
  {
    projectId: "PRO-SHOPPING",
    id: "TSK-L5zreBgE",
    title: "Kidney Beans",
    description: null,
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-26T23:23:28.916Z",
    lastModifiedDateTime: "2025-09-26T23:23:28.916Z",
  },
  {
    projectId: "PRO-SHOPPING",
    id: "TSK-ynRgJSnT",
    title: "Tortilla",
    description: null,
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-26T23:21:01.620Z",
    lastModifiedDateTime: "2025-09-26T23:21:01.620Z",
  },
  {
    projectId: "PRO-SHOPPING",
    id: "TSK-s4FYelNe",
    title: "Lettuce",
    description: null,
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-26T23:20:23.023Z",
    lastModifiedDateTime: "2025-09-26T23:20:23.023Z",
  },
  {
    projectId: "PRO-SHOPPING",
    id: "TSK-Ex6OVaAE",
    title: "Bacon",
    description: null,
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-26T21:27:44.382Z",
    lastModifiedDateTime: "2025-09-26T21:27:44.382Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-3zgFjL8S",
    title: "Create Options Modal for Projects",
    description:
      "Need to be able to create, edit, & delete projects. Can do this by adding an options icon to the top right of /projects/[projectId] that slides open to 'edit or delete', clicking edit opens a modal that shows editor.",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-26T21:19:49.872Z",
    lastModifiedDateTime: "2025-10-07T17:30:25.709Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-bUrmhW8S",
    title: "Fix Checkboxes",
    description:
      "Each Task has a Checkbox next to it on the /projects/[projectId] page.\n\nThe user should be able to select one-or-many checkbox, with floating sticky buttons for 'Mark as done' & 'Delete' & eventually 'Tag'\n\nIf the user checks a box, all already checked boxes must be disabled, vice versa. When checking boxes, use a different color then the blue used when selected.",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-24T22:11:36.990Z",
    lastModifiedDateTime: "2025-10-02T23:58:49.153Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-GYsmEgIb",
    title: "Submitting Multiple Tasks",
    description:
      "When trying to submit a second Task (without refreshing), it seems like the form is cleared, but the task was not added.",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-24T22:08:49.096Z",
    lastModifiedDateTime: "2025-10-02T00:35:19.134Z",
  },
  {
    projectId: "PRO-GvUg9na4",
    id: "TSK-bkzR6RFy",
    title: "TaskProgrammer - 2",
    description:
      "- Improve textareas to support bulleted lists, bolding headers (markdown - https://www.markdownguide.org/)\n\n- Since each Project is a coding session, add 'Create Commit Message' button that can ping chatGPT API to prompt using each Task in the Project",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-24T22:07:33.823Z",
    lastModifiedDateTime: "2025-09-24T22:07:33.823Z",
  },
  {
    projectId: "PRO-GvUg9na4",
    id: "TSK-AlsbWpbt",
    title: "TaskProgrammer - 1",
    description:
      "Could slightly alter this app to better support Task-Oriented programming.\n\nFor example, I could add an additional textarea in this form for 'Ideas to get started'.\nEssentially make a barebones version of Github Issues for local/smaller tasks.",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-24T21:58:33.565Z",
    lastModifiedDateTime: "2025-09-24T21:58:33.565Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-eSR3HmRD",
    title: "Add Grouping for Tasks",
    description:
      "Within a Project, someone may want the ability to group certain Tasks together. I could create a Group class that can be created within a Project which you could add individual Tasks. I could also just add a property to Task.'tags' : Array<String>.",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-24T21:51:00.747Z",
    lastModifiedDateTime: "2025-09-24T21:51:00.747Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-Dtsm5amK",
    title: "Reference Tasks in Task",
    description:
      "When creating my last task, I needed to reference a task that already exists in the project. I should try to implement a means to reference other Tasks within a Task. Could use '@' to signal an autocomplete to look for tasks.",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-24T21:43:54.071Z",
    lastModifiedDateTime: "2025-09-24T21:43:54.071Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-cs9gkUb4",
    title: "Edit Task UI",
    description:
      "Similar to the Task Addition UI task, need to update the UI when a task is edited on page: tasks/[taskId]/edit\n\nChanges are immediately shown in UI on successful Task update ",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-24T21:42:08.617Z",
    lastModifiedDateTime: "2025-10-02T20:09:10.549Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-NAiqU3wa",
    title: "Task Addition UI",
    description:
      "If a Task is successfully created, the UI should respond with more than just clearing the form. Also, the newly created Task should immediately be visible below the form accordion if the server responds with no errors.\n\nDONE: SpninnerComponent shows Task addition status & accordion is closed on success. ",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-24T21:11:46.625Z",
    lastModifiedDateTime: "2025-10-02T00:42:44.108Z",
  },
  {
    projectId: "PRO-GvUg9na4",
    id: "TSK-Uo7GDHsQ",
    title: "Custom Navigation",
    description:
      "Have some standard site (todo, blog, etc.). The whole aim of the site is that the user can fully customize the navigation. The idea almost like ordering iphone apps. The user will be able to drag/drop/resize all windows/components/nav links",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-24T21:09:13.988Z",
    lastModifiedDateTime: "2025-09-24T21:09:13.988Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-gdj1jEJM",
    title: "Fix Back Button Navigation",
    description:
      "The back button navigation is inconsistent. Example being when viewing a specific Task from /projects/[projectId].\n\nThis is because /tasks/[taskId] is the page route used. This is used both here and at /tasks\n\nCould dupe the page to have a separate route",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: "2025-09-25T08:00:00.000Z",
    creationDateTime: "2025-09-24T21:04:12.334Z",
    lastModifiedDateTime: "2025-10-01T00:39:51.153Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-JYaLMiwI",
    title: "Fix linting errors",
    description:
      "Running the pnpm lint command will help catch static errors\nNeed to build project to catch other potential errors (pnpm build)\nThere may be additional errors caught at the production level once the code is pushed",
    isDone: true,
    ordinal: null,
    expectedCompletionDateTime: "2025-09-26T04:00:00.000Z",
    creationDateTime: "2025-09-24T20:23:39.233Z",
    lastModifiedDateTime: "2025-10-05T21:55:20.799Z",
  },
  {
    projectId: "PRO-SHOPPING",
    id: "TSK-yupL7i1g",
    title: "Paper Towels",
    description: "Better be double-plyed!!!",
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-12T03:03:06.531Z",
    lastModifiedDateTime: "2025-09-12T03:15:59.055Z",
  },
  {
    projectId: "PRO-SHOPPING",
    id: "TSK-iXdsxnbD",
    title: "Bananas",
    description: null,
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-11T20:48:13.350Z",
    lastModifiedDateTime: "2025-09-11T20:48:13.350Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-UGLrCWNL",
    title: "Refine Mockups",
    description:
      "Using Figma, update wireframes to better reflect the current design",
    isDone: true,
    ordinal: 1,
    expectedCompletionDateTime: "2025-09-13T16:48:00.000Z",
    creationDateTime: "2025-09-11T20:48:13.350Z",
    lastModifiedDateTime: "2025-10-01T00:52:10.836Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-3Bo8TXoE",
    title: "Create Wireframes",
    description: "Description . . .",
    isDone: true,
    ordinal: 0,
    expectedCompletionDateTime: "2025-09-11T20:48:13.350Z",
    creationDateTime: "2025-09-11T20:48:13.350Z",
    lastModifiedDateTime: "2025-09-11T20:48:13.350Z",
  },
  {
    projectId: "PRO-SHOPPING",
    id: "TSK-myPYkH4I",
    title: "Tomatos",
    description: null,
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-11T20:48:13.350Z",
    lastModifiedDateTime: "2025-09-11T20:48:13.350Z",
  },
  {
    projectId: "PRO-SHOPPING",
    id: "TSK-pwRv4O6J",
    title: "Rice",
    description: null,
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-11T20:48:13.350Z",
    lastModifiedDateTime: "2025-09-11T20:48:13.350Z",
  },
  {
    projectId: "PRO-SHOPPING",
    id: "TSK-8AKL65jL",
    title: "Black Beans",
    description: null,
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-11T20:48:13.350Z",
    lastModifiedDateTime: "2025-09-11T20:48:13.350Z",
  },
  {
    projectId: "PRO-SHOPPING",
    id: "TSK-mJs98xZe",
    title: "Oranges",
    description: null,
    isDone: false,
    ordinal: null,
    expectedCompletionDateTime: null,
    creationDateTime: "2025-09-11T20:48:13.350Z",
    lastModifiedDateTime: "2025-09-11T20:48:13.350Z",
  },
  {
    projectId: "PRO-TODOAPP",
    id: "TSK-DroHiSv2",
    title: "Implement JS Skeleton",
    description: "Description . . .",
    isDone: true,
    ordinal: 2,
    expectedCompletionDateTime: "2025-09-14T00:48:00.000Z",
    creationDateTime: "2025-09-11T20:48:13.350Z",
    lastModifiedDateTime: "2025-10-01T00:49:29.702Z",
  },
];

export const Projects = [
  {
    id: "PRO-UEgZgZMLUEus",
    name: "Project To Be Deleted II",
    description: null,
    hexColor: null,
    icon: null,
    creationDateTime: "2025-10-09T21:27:06.827Z",
    lastModifiedDateTime: "2025-10-10T23:26:49.550Z",
  },
  {
    id: "PRO-FwHRKp5O",
    name: "Form Submission Success Animation",
    description:
      "This project eventually became the 'spinner.tsx'  component and is used in Task creation. Lets see how quickly the projects are updated.",
    hexColor: "5cf6",
    icon: "🏋️",
    creationDateTime: "2025-09-26T23:51:39.815Z",
    lastModifiedDateTime: "2025-10-06T23:14:22.712Z",
  },
  {
    id: "PRO-GvUg9na4",
    name: "Potential Projects",
    description: null,
    hexColor: "8b5cf6",
    icon: null,
    creationDateTime: "2025-09-24T21:05:49.104Z",
    lastModifiedDateTime: "2025-10-07T16:22:18.919Z",
  },
  {
    id: "PRO-TODOAPP",
    name: "Todo App",
    description:
      "A list of bugs & improvements that I think of while programming.",
    hexColor: "EEFC57",
    icon: null,
    creationDateTime: "2025-09-11T20:48:13.350Z",
    lastModifiedDateTime: "2025-10-05T17:27:53.593Z",
  },
  {
    id: "PRO-SHOPPING",
    name: "Shopping List",
    description: "This is the main testing project for adding Tasks!",
    hexColor: "ec4899",
    icon: null,
    creationDateTime: "2025-09-11T20:48:13.350Z",
    lastModifiedDateTime: "2025-10-09T18:52:18.674Z",
  },
];
